spring:
  application:
    name: batch

  config:
    import:
      - classpath:application-db.yml
      - classpath:application-tmdb.yml

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: "9f8d4291600c08f23acc054d6ef6b01a"
            client-secret: "Zm77k1PZsjwogT8BlE4fRDmBMSPSqhbU"
            client-name: Kakao
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: 28cc7c3ad555cbc501c98419fa8d56c057db935505084ff44a6d6156c9c9f15c
  expire:
    access-token: 1
    refresh-token: 24